package com.samrit.job.domain;

public enum IndustryType {
    TECHNOLOGY,
    FINANCE_BANKING,
    HEALTHCARE,
    EDUCATION,
    MANUFACTURING,
    HOSPITALITY_TOURISM,

    RETAIL_ECOMMERCE,
    REAL_STATE,
    MEDIA_ENTERTAINMENT,
    TRANSPORTATION_LOGISTICS,
    ENERGY_UTILITIES,
    AGRICULTURE,
    CONSULTING,
    LEGAL,
    TELECOMMUNICATIONS,
    AUTOMOTIVE,
    PHARMACEUTICAL,
    CONSTRUCTION,
    HUMAN_RESOURCES,
    MARKETING_ADVERTISING,
    OTHER

}
